name: Weekly Security Check

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dependabot security audit
        run: |
      - name: Run Code Scanning
